[versions]
agp = "8.7.2"
browser = "1.8.0"
charts = "1.3.1"
coilCompose = "2.7.0"
compose = "1.15.0"
composeM2 = "1.15.0"
composeM3 = "1.15.0"
converterGson = "2.11.0"
core = "1.15.0"
hiltAndroid = "2.52"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxSerializationJson = "1.6.3"
ktorClientAndroid = "2.3.0"
ktorClientAuth = "2.x.x"
ktorClientAuthVersion = "2.3.0"
ktorClientCio = "3.0.1"
ktorClientContentNegotiation = "2.x.x"
ktorClientContentNegotiationVersion = "2.3.0"
ktorClientCore = "3.0.1"
ktorClientCoreVersion = "2.3.0"
ktorClientSerialization = "3.0.1"
ktorSerializationGson = "2.x.x"
ktorSerializationGsonVersion = "2.3.0"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.3"
composeBom = "2024.04.01"
lifecycleViewmodelCompose = "2.8.6"
navigationCompose = "2.8.3"
sqliteKtx = "2.5.0-alpha10"
material = "1.8.0-alpha04"
datastorePreferences = "1.1.1"
animation = "1.7.4"
material3 = "1.4.0-alpha02"
materialIconsExtended = "1.7.4"
hiltNavigationCompose = "1.2.0"
billingKtx = "7.1.1"
views = "1.15.0"

[libraries]
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
billing = { module = "com.android.billingclient:billing" }
billing-ktx = { module = "com.android.billingclient:billing-ktx" }
charts = { module = "io.github.dautovicharis:charts" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose = { module = "com.patrykandpatrick.vico:compose", version = "2.0.0-beta.3" }
compose-m2 = { module = "com.patrykandpatrick.vico:compose-m2", version = "2.0.0-beta.3" }
compose-m3 = { module = "com.patrykandpatrick.vico:compose-m3", version = "2.0.0-beta.3" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core = { module = "com.patrykandpatrick.vico:core", version = "2.0.0-beta.3" }
dautovicharis-charts = { module = "io.github.dautovicharis:charts", version.ref = "charts" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0-alpha02" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.0-alpha01" }
androidx-sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqliteKtx" }
androidx-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorClientAuth" }
ktor-client-auth-v230 = { module = "io.ktor:ktor-client-auth", version.ref = "ktorClientAuthVersion" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-content-negotiation-v230 = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiationVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-core-v230 = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCoreVersion" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorClientSerialization" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktorSerializationGson" }
ktor-serialization-gson-v230 = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktorSerializationGsonVersion" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0-alpha02" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
billingclient-billing-ktx = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billingKtx" }
views = { module = "com.patrykandpatrick.vico:views", version = "2.0.0-beta.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

